sudo: required

language: go

services:
  - docker

env:
  - DOCKER_BIND_LOCALHOST=true

go:
  - master

install:
  - go get github.com/mattn/goveralls golang.org/x/tools/cmd/cover github.com/pierrre/gotestcover github.com/Masterminds/glide
  - glide install

script:
  - go vet -x .
  - gotestcover -coverprofile="cover.out" -race -covermode="count" .
  - goveralls -coverprofile="cover.out"
